server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: sayjong-backend

  # DB(MySQL)
  datasource:
    url: "jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  batch:
    jdbc:
      platform: mysql