name: Deploy Backend to GCP

on:
  push:
    branches:
      - main # main 브랜치에 push 될 때 실행됩니다.

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'

    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle 실행 권한 부여
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 4. Spring Boot 애플리케이션 빌드
      - name: Build with Gradle
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: ./gradlew bootJar

      # 5. JAR 파일 이름 변경
      - name: Rename JAR file
        run: mv build/libs/*.jar build/libs/app.jar

      # 6. 빌드된 JAR 파일을 GCP 서버로 전송
      - name: Copy JAR to GCP VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          port: 22
          source: "build/libs/app.jar"
          target: "/home/deployer/app/"

      # 7. GCP VM에서 애플리케이션 재시작
      - name: Deploy on GCP VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            sudo systemctl restart sayjong-backend